### ISSUE TITLE
Feature request: support provider.deploymentBucket.blockPublicAccess

### ISSUE THREAD

**Issue by mfogel** [MikeSouza/serverless-deployment-bucket#31] opened 2020-11-25 15:04 UTC
Hi, thanks for your work putting this project together. Much appreciated

It appears `serverless-deployment-bucket` doesn't pick up on the `provider.deploymentBucket.blockPublicAccess` key in serverless.yml. I realize it's possible to [set an exact bucket policy](https://github.com/MikeSouza/serverless-deployment-bucket/issues/15#issuecomment-674872243), but it seems likely that a common use case is to want to block all public access, and when not using this plugin that can be done with just:

```yml
provider:
  deploymentBucket:
    blockPublicAccess: true
```

For reference, here's how this was [implemented in serverless core](https://github.com/serverless/serverless/pull/6779)

**Comment by cganesan66** [comment] 2020-11-25 17:08
I am using this plugin as well and thanks for that. I think adding the above feature to block public access will be very useful. Please let us know if you plan to implement it.

**Comment by jdrydn** [comment] 2021-03-06 10:57
For reference: Just added this plugin & noticed the block public access settings are indeed "off"!

@MikeSouza If this isn't something you're currently working on, do you mind if I create a PR with the relevant changes for you to review?

**Comment by MikeSouza** [comment] 2021-03-06 14:29
A PR is welcomed. As I do not have the time to work on this. Just please
add tests and ensure coverage remains 100%.

**Comment by MikeSouza** [comment] 2021-03-06 18:04
@jdrydn Yes, please feel free to make a PR. I don’t have the time right now and would appreciate the help. Please just make sure to write init tests and maintain the 100% coverage, and I’ll happily review. Thanks.

**Comment by MikeSouza** [comment] 2021-03-07 19:59
@jdrydn Thank you for the contribution.  Merged and released in v1.4.0.

**Closed by MikeSouza** 2021-03-07 19:59 UTC

**Comment by coyoteecd** [comment] 2021-03-25 15:32
@jdrydn @MikeSouza I can't get this to work, my bucket is always created with blockPublicAccess=off

I think the cause is [here](https://github.com/MikeSouza/serverless-deployment-bucket/blob/4d2e851e92f3ed79ad8dea0bb17f235eadff1b4a/lib/index.js#L205); when I deploy the bucket is created and the getPublicAccessBlock throws an error with code 'NoSuchPublicAccessBlockConfiguration'.

If I check on the code and return true, then the plugin creates the PublicAccessBlock config and next time the error is not thrown anymore.

**Comment by jdrydn** [comment] 2021-03-25 18:27
Ahhh, when a bucket is initially created it'll never set the public-access settings because there isn't a public-access result on the bucket (durr, it's new) to calculate a change! My mistake there is assuming there would be a `null` result from `getPublicAccessBlock` on a new bucket rather than throwing an error 🤦‍♂️ 

@MikeSouza I'll push a fix shortly & open a PR for you to review 🎉
